version: "3"
services:
  service-a:
    build: ./service-a
    container_name: service_a
    ports:
      - "5001:5001"

  service-b:
    build: ./service-b
    container_name: service_b
    ports:
      - "5002:5002"
    depends_on:
      - service-a
